modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "valkyrienmanager"
version = "${version}"
displayName = "Valkyrien Skies Manager"
authors = "Me!"
description = '''
Makes your life easier with lots of ships. Fire Ship events to kjs, computer craft, query ship data extension through api
'''
#logoFile = ""

[[dependencies.valkyrienmanager]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrienmanager]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrienmanager]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
